### ISSUE TITLE
Lambda in Protocol/Transaction class

### ISSUE THREAD

**Issue by kodaman2** [EPICSTools/etherip#24]
Is there any particular reason why one class out of the whole project is using lambda?
Project might reach more people that are still running in java 1.7

The only sole reason why the project doesn't compile in java 1.7 is because the lambda function which then gets converted to regular anonymous function, problem is LongBinaryOperation class doesn't exist in 1.7

Modified code, ran Transaction unittest and passed:
```
static long nextTransaction()
    {

        if(transaction.get() > 0xffffffffL){
            transaction.set(1);
        } else{
            transaction.incrementAndGet();
        }

        return transaction.get();

```
Original code below:
```

        return transaction.incrementAndGet(1, new LongBinaryOperator() {
            @Override
            public long applyAsLong(long value, long plus) {
                long result = value + plus;
                if (result > 0xffffffffL)
                    return 1;
                return result;
            }
        });
    }
```
I will test in the plc lab, anyways my usage doesn't require tons of transactions I highly doubt I will ever get to the max,I just need to read some tags for a backup utility I am building, and all our servers run on 1.7 and I don't foresee IT's updating anytime soon.

**Comment by kasemir** [comment]
You're mixing lambda and atomic operation.

No, it doesn't have to use a lambda. I'm OK with Java 1.7.
But it has to be atomic.

`AtomicLong.accumulateAndGet(..)` is, well, atomic, as the name applies.
`if (AtomicLong.get() .. )    ...AtomicLong.incrementAndGet()` is not atomic. Another thread could jump in between the `get` and the `increment` call.
You might not see that for a long time in running unit tests, but it's not atomic.

Java 7  has https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/atomic/AtomicLong.html, so make a pull request that uses that. If not possible, make a suggestion that adds `synchronized`.

**Comment by kodaman2** [comment]
` private static final AtomicLong transaction = new AtomicLong(0);`

Sorry for the mixup, yeah transaction still atomic. Haven't used much lambda to be honest, but in short what I was attempting to say was that when I made the lambda to anonymous function, LongBinaryOperator doesn't exist in 1.7

Will make PR then. By the way just tested with both L7, and L8 controllers and I was able to connect and read tags. I wasn't sure if I would be able to read Program tags since there is a power point of the etherip on the c repo, and specifically says no program tags. 

![image](https://user-images.githubusercontent.com/10265682/45493851-54e14800-b735-11e8-951c-e40b94680827.png)

**Comment by kasemir** [comment]
As for program tags, in all the setups I've tried we could only access controller tags.
In a way that good, you have control over what's accessible. Program tags remain hidden.
Beware, though, that those automatically created controller tags for all the I/O modules are, well, controller tags, so you can read/write those. No way to hide them from network access.

**Comment by kodaman2** [comment]
I'll revise to non-blocking, by the way I tested and is overflowing because with original code it was a long binary, Atomic class uses long, so just need to make some adjustments and will make some proper unit tests to make sure it goes back to 1 when going over 0xffffffffL

**Comment by kodaman2** [comment]
This is what I came up with finally:

```
private static final AtomicLong transaction = new AtomicLong(0);

    static long nextTransaction()
    {
        synchronized (Transaction.class){
            if(transaction.get() > 0xffffffffL){
                transaction.set(1);
            } else{
                transaction.incrementAndGet();
            }

            return transaction.get();
        }
    }
```
Will need to research how to properly unittest nonblocking, because I've never done it before, but for my purposes everything works good on my lab. On my utility I only read less than 20 tags, so I don't foresee any issues. Either way I'll make PR, or you can just point to my repo on your readme if someone is interested in downgraded 1.7 and that way there are two options.

A better choice is probably to compile the jar for this repo and name it 1.8, and then compile the 1.7 and place both jar in a folder.

**Comment by kasemir** [comment]
When you're using synchronized, you can remove the AtomicLong and instead use a plain long because you are blocking in synchronized. Any potential benefit from AtomicLong is lost.
So this would do it:

// SYNC on access
private long transaction;
```
static long nextTransaction()
{
    synchronized(Transaction.class)
    {
        ++transaction;
        if (transaction > 0xffffffffL)
            transaction = 1;
        return transaction;
}
```

**Comment by kodaman2** [comment]
Refer to [PR#25](https://github.com/EPICSTools/etherip/pull/25) for more information.
