### ISSUE TITLE
Read single tag from AB CompactLogix 5380

### ISSUE THREAD

**Issue by MichaelMS91** [EPICSTools/etherip#32]
Hello!

I am using an Allen-Bradley CompactLogix 5380. I am able to connect with this device but when I try to read tags with _readTag_ function, it happens an exception.

My connection is established just like:

`
 EtherNetIP plc = new EtherNetIP(mIp,mId);
        try {
            plc.connectTcp();            
        } catch (CipException cipe){`

And my reading code is like:

`
String message = "var1";
CIPData data = null;
        try {
            data = plc.readTag(message);
        } catch (CipException cipe){
                  ...
`

I am trying to read _var1_ variable which is its name in my PLC. I have declared it as _Local Tag_ in _my MainRoutine_ and later as _Output Parameter_ and _Public Parameter_ with _Producer_ Type. I declared it also as a _Tag_ in _Controller Tags_ but always I receive the same error:

**etherip.data.CipException: Status: 0x01** _[Connection failure, A connection related service failed along the connection path.] - Extended: 0x312 [LINK ADDRESS NOT VALID, Link Address specified in Port Segment Not Valid This extended status code is the result of a port segment that specifies a link address that is not valid for the target network type. This extended status code shall not be used for link addresses that are valid for the target network type but do not respond.]_

Could someone tell me how to read that tag? Must I do anything more before trying to read it? 

Thanks in advance

**Comment by kasemir** [comment]
What is your 'mId' in `new EtherNetIP(mIp,mId)`?

**Comment by kasemir** [comment]
Also add something like `Logger.getLogger("").setLevel(Level.ALL);` to get a complete output of everything read and written to better see where it fails.

**Comment by MichaelMS91** [comment]
> 
> 
> What is your 'mId' in `new EtherNetIP(mIp,mId)`?

It was the Id that I assigned to the PLC. It was wrong, its value was 1 instead of 0. When I changed it, the program started to run normally.

Thanks a lot!

**Comment by kasemir** [comment]
Yeah, 'slot' needs to be the slot number, counting from 0, of the controller on the backplane.
