### ISSUE TITLE
Using EtherNetIP and Connection

### ISSUE THREAD

**Issue by aaron-bru** [EPICSTools/etherip#36]
Hello, I need to be able to use the EtherNetIP class, as well as its underlying Connection, specifically the execute() and getSession() methods. I'm using a simple accessor, but I'm happy to submit a different pull request. Some ideas are:

- getConnection() accessor
- exposing execute() and getSession() in EtherNetIP
- Adding a dependency injection constructor or initializer to allow passing in a Connection object

Thanks

**Comment by kasemir** [comment]
Adding an accessor like `getConnection()` is fine, please go ahead with PR.
