### ISSUE TITLE
Add to CNService enum

### ISSUE THREAD

**Issue by aaron-bru** [EPICSTools/etherip#37]
Hello, I need to add some values to the CNService enum, I'm not sure if this is something you'd want merged in or not. If so the ones I need are ForwardOpen(0x54) and ForwardClose(0x4E) which I can submit.

Alternatively, I've read the easiest way to allow adding at runtime is to have the enum implement an interface which is used throughout the library, which other applications can then implement as needed. I don't mind attempting this if it's preferred.

**Comment by kasemir** [comment]
Adding those values is fine, please go ahead with PR.
