### ISSUE TITLE
Problems compiling etherip classes

### ISSUE THREAD

**Issue by jonwolf-ibisa** [EPICSTools/etherip#5]
Hi, I'm having problems compiling the classes, I've tried putting the files like in the package structure, each file inside its directory but I'm always getting import errors when compiling, could you please tell me how to compile all the classes, how to locate them in the directories, thanks in advance

**Comment by kasemir** [comment]
The sources are currently in the form of an Eclipse project:

Get Eclipse, import project, then run any of the test/* classes.
They are in the form of JUnit tests. Those named *Test.java are actual tests. Those named *Demo.java are not meant to be basic unit tests, but instead more like demonstration programs where you will need to change the IP address of your PLC and check if your PLC has the tags that the demo code tries to read or write.
