### ISSUE TITLE
Reading Tags with a dot

### ISSUE THREAD

**Issue by MxBlinkPx** [EPICSTools/etherip#8]
Is there a way to read tags with a dot in the name? Like 'Test.Me'?

**Comment by kasemir** [comment]
Have you tried it? The tags are simply passed through, so it really depends how the PLC handles the ".". I believe that the PLC uses the "." to separate fields of structures. With the C implementation of the driver, that allowed reading fields of structures, as long as those fields were plain tags, not structures.

**Comment by csobsidian** [comment]
There are some examples of what the message frames should like like for accessing members of user-defined structures in [Logix5000 Data Access](http://literature.rockwellautomation.com/idc/groups/literature/documents/pm/1756-pm020_-en-p.pdf).

**Comment by MxBlinkPx** [comment]
Thanks, I got it working with Wireshark, if anyone is curious, this worked for me. Tag was also modified to support element counts. With this you can request like: Test.Big[2].Running

    public class CNSymbolMultiPath extends CNPath{
	    class PathAndIndex{
		private String path;
		private Integer index;
		public PathAndIndex(String path, Integer index) {
			this.path = path;
			this.index = index;
		}
		public String getPath() {
			return path;
		}
		public Integer getIndex() {
			return index;
		}
		
	   };
	
	private final Pattern PATTERN_BRACKETS = Pattern.compile("\\[(\\d+)\\]");
	
	private List<PathAndIndex> paths = new ArrayList<>();
	
	/** Initialize
	 *  @param symbol Name of symbol
	 */
	protected CNSymbolMultiPath(final String symbol)
	{
		for(String s:symbol.split("\\.")){
			Matcher m = PATTERN_BRACKETS.matcher(s); 
			Integer index = null;
			String path = s;
			while(m.find()){
				String match = m.group().replace("[","").replace("]", "");
				index = Integer.parseInt(match);
				path = path.replace("[" + match + "]", "");
			}
			paths.add(new PathAndIndex(path, index));
		}
	}
	
    /** {@inheritDoc} */
	@Override
    public int getRequestSize()
    {   // End of string is padded if length is odd
		int count = 0;
		for(PathAndIndex s:paths){
			count += 2 + s.getPath().length() + (needPad(s.getPath()) ? 1 : 0);
			if(s.getIndex()!=null)
				count += 2;
		}
		return count;
    }
    
    /** {@inheritDoc} */
	@Override
    public void encode(final ByteBuffer buf, final StringBuilder log)
	{
		// spec 4 p.21: "ANSI extended symbol segment"
		buf.put((byte) (getRequestSize() / 2));
		for(PathAndIndex pi:paths){
			String s = pi.getPath();
			buf.put((byte) 0x91);
			buf.put((byte) s.length());
			buf.put(s.getBytes());
			if (needPad(s))
				buf.put((byte) 0);
			Integer index = pi.getIndex();
			if(index!=null){
				//Path Segment 28, from wireshark
				buf.put((byte) 0x28);
				buf.put(index.byteValue());
			}
		}
		
	}

	/** @return Is path of odd length, requiring a pad byte? */
	private boolean needPad(String s)
    {
	    // Findbugs: x%2==1 fails for negative numbers
	    return (s.length() % 2) != 0;
    }
}

**Comment by kasemir** [comment]
Excellent!
Should I update the existing class `CNSymbolPath` with the functionality of your `CNSymbolMultiPath`? Or do you see any reason why one would _not_ parse a received tag into path elements?

**Comment by MxBlinkPx** [comment]
I've only used Ethernet/IP this one time, so I can't say for certain, but I think it should work. I also recommend adding the element count to Tag, I can lookup how I did it later if you need it, but it's pretty straight forward.

**Comment by jgmurray23** [comment]
I think I am having a similar problem - did this ever get pulled into the main branch or how could I test this, help if possible?

**Comment by kasemir** [comment]
No, hasn't been pulled. If you can try it, also checking that plain tags without dots still work, and create a pull request, I'll merge it.

**Comment by wz2b** [comment]
I just tested MxBlinkPx's patch:

1. Getting dptest.T worked (single attribute out of a struct)

2. Getting DataTable[4].T  worked (single attribute out of an array of structs)

3. Getting intarr[3] worked (a single DINT out of an array of DINT)

4. Getting IntTag worked (a single DINT with no dot)

so to answer your question, it does work with plain tags (without dots) and it doesn't break anything.

I made it its own separate class, but a where-used suggests that CNSymbolPath is not used anywhere else so I think it's OK to just replace it - this one always seems to do the right thing.

**Comment by wz2b** [comment]
Also: I tested it with odd-length strings (for both the tag name and the attribute name) to make sure that adding that extra 00 for padding of odd-length strings still works.  It works correctly.

**Comment by kasemir** [comment]
Thanks a lot for testing it. I agree with replacing the existing CNPath with the one that correctly cuts tags into path elements. Please create a pull request.

**Comment by kasemir** [comment]
@wz2b thanks for fixing this!
